//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeMaster
    {
        public int SchemeID { get; set; }
        public string SchemeName { get; set; }
        public int Createdby { get; set; }
        public int Creaateddate { get; set; }
    }
}
